
# SEO settings
title: "Portalonthe.Rocks"
# title2: "space" # default: ""
description: "Blog around CRM Portals"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: /blog # site url
# baseurl: "portalontherocks.github.io/blog" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/portalontherocks/blog
disqus_shortname: "portalontherocks"

comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Tino Rabe"
  job      : "Learner"
  bio      : "Knowing a little more about the unknown everyday."
 # thumb    : /images/author.jpg
  email    : rabetino@me.com
 # url      : http://heiswayi.github.io
 # github   : http://github.com/portalontherocks
 # twitter  : http://twitter.com/HeiswayiNrird
 # facebook : https://www.facebook.com/heiswayi.nrird
 # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "de_DE"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
